["zhipu"]
model = "glm-4"
key = "5212184cf576db88f5fb8addc4b8603e.37c8W9ifp5HhAhJ7"
base_url = "https://open.bigmodel.cn/api/paas/v4/"
dir_path = "../sourceData/data"
top_k = 15
embedding_path = "F:/PycharmProject/model/models--iampanda--zpoint_large_embedding_zh"
question_path = "question.jsonl"