["zhipu"]
model = "glm-4"
key = "8c757cde7cff11fe0e13137bc38679a1.gaSN5dlpnoK2GjTg"
base_url = "https://open.bigmodel.cn/api/paas/v4/"
dir_path = "../sourceData/data"
top_k = 50
embedding_path = "F:/PycharmProject/model/models--iampanda--zpoint_large_embedding_zh"
question_path = "question.jsonl"